use_frameworks!

platform :ios, '9.0'

target 'CorrectAnimationRefreshControl_Example' do
  pod 'CorrectAnimationRefreshControl', :path => '../'

  target 'CorrectAnimationRefreshControl_Tests' do
    inherit! :search_paths

    
  end
end
